### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by tyouika** [owennewo/musicxml-ts#1]
Hello, I don't know how to run this project, please add some guides，thanks.

**Comment by owennewo** [comment]
This was a play/experiment project I was working on about a year ago.  Whilst it was working for me - it looks like its dependencies have moved on and/or I've not checked in a few files.

If I remember correctly - the project can read in musicxml files - converting xml to typed objects and then attempted to display it as SVG in a web browser.  It was OK with very simple music notation (a couple of bars) but I got put off by the mountain of effort required to map the minutae of musicxml into SVG.

The only type of person that might be interested in this project is a developer who wants to do something similar.  I'm happy to spend a few hours patching it up - but I suspect you won't be that impressed at the progress I made!  Realistically this type of project would need 100 to a 1000 hrs before an end user might consider it usablable and I probably spent nearer 10-20hrs on it.

**Comment by tyouika** [comment]
Thank you very much. This is very helpful to me.
